sudo: required
services: 
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t mzdanavicius2/multi-client ./client
  - docker build -t mzdanavicius2/multi-nginx ./nginx
  - docker build -t mzdanavicius2/multi-server ./server
  - docker build -t mzdanavicius2/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mzdanavicius2/multi-client
  - docker push mzdanavicius2/multi-nginx
  - docker push mzdanavicius2/multi-server
  - docker push mzdanavicius2/multi-worker